[package]
name = "parquess"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = { version = "1.0.75", features = ["backtrace"] }
arrow = "48.0.0"
bpaf = { version = "0.9.5", features = ["derive"] }
crossterm = "0.27.0"
hsl = "0.1.1"
parquet = "48.0.0"
