[package]
name = "tass"
description = "A pager for tabular data"
version = "0.4.0"
authors = ["Alex Sayers <alex@asayers.com>"]
edition = "2018"
license = "Unlicense"
readme = "README.md"
repository = "https://github.com/asayers/tass"

[dependencies]
anyhow = "1.0"
clap = { version = "3.0.10", features = ["derive"] }
crossterm = "0.22.1"
csv = "1.1"
grep-matcher = "0.1"
grep-regex = "0.1"
grep-searcher = "0.1"
hsl = "0.1"
memchr = "2.3"
ndarray = "0.15.4"
once_cell = "1.7.0"
pad = "0.1"
tempfile = "3.1"
