[package]
name = "tess"
version = "0.1.0"
authors = ["Alex Sayers <alex@asayers.com>"]
edition = "2018"

[dependencies]
crossterm = "0.17.1"
csv = "1.1.3"
tabwriter = "1.2.1"
anyhow = "1.0.28"
structopt = "0.3.12"
memchr = "2.3.3"
memmap = "0.7.0"
ndarray-csv = "0.4.1"
ndarray = "0.13.0"
pad = "0.1.6"
