[package]
name = "tess"
description = "A pager for tabular data"
version = "0.1.0"
authors = ["Alex Sayers <alex@asayers.com>"]
edition = "2018"
license = "Unlicense"
readme = "README.md"
repository = "https://git.sr.ht/~asayers/tess"

[dependencies]
anyhow = "1.0"
crossterm = "0.18"
csv = "1.1"
grep-matcher = "0.1"
grep-regex = "0.1"
grep-searcher = "0.1"
memchr = "2.3"
memmap = { version = "0.7", optional = true }
ndarray = "0.13"
ndarray-csv = "0.4"
pad = "0.1"
structopt = "0.3"
tempfile = "3.1"
