[package]
name = "tass"
description = "A pager for tabular data"
version = "0.6.0"
authors = ["Alex Sayers <alex@asayers.com>"]
edition = "2021"
license = "Unlicense"
readme = "README.md"
repository = "https://github.com/asayers/tass"

[dependencies]
anyhow = { version = "1.0.75", features = ["backtrace"] }
arrow = { version = "49", features = ["chrono-tz"] }
bpaf = { version = "0.9.6", features = ["derive"] }
chrono = "0.4.31"
chrono-tz = "0.8.4"
crossterm = "0.27.0"
fileslice = { version = "0.3.0", default-features = false }
hsl = "0.1.1"
memchr = "2.6.4"
parquet = "49"
tempfile = "3.8.1"
tracing = "0.1.40"
tracing-subscriber = { version = "0.3.18", features = ["env-filter"] }
